variables:
    projectname: QuanLyTuyenDung
    version: 0.0.1-SNAPSHOT
    projectuser: QuanLyTuyenDung
    projectpath: /datas/$projectuser/


stages:
    - build
    - deploy
    - showlog

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - mvn install -DskipTests=true
    tags:
        - practice-devops
    only:
        - tags

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - sudo cp target/$projectname-$version.jar $projectpath
        - sudo chown $projectuser. $projectpath
        - sudo su $projectuser -c "kill -9 $(ps -ef| grep QuanLyTuyenDung-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}')"
        - sudo su $projectuser -c "cd $projectpath; nohup java -jar $projectname-$version.jar > nohup.out 2>&1 &"
    tags:
        - practice-devops
    only:
        - tags

showlog:
    stage: showlog
    variables:
        GIT_STRATEGY: none
    script:
        - sleep 20
        - sudo su $projectuser -c "cd $projectpath; tail -n 10000 nohup.out"
    tags:
        - practice-devops
    only:
        - tags
